project:
  type: website
  output-dir: _site

extensions:
  - path: _extensions/grantmcdermott/clean/_extension.yml

website:
  title: "ğŸ¥¼ RESEARCH"
  bread-crumbs: true
  navbar:
    right:
      - href: ai-learning-circle/index.qmd
        text: ğŸ¤– AI Learning Circle
      - href: projects/index.qmd
        text: ğŸ“‚ Projects
      - href: https://lpcordova.com
        text: â† LPCORDOVA


format:
  html:
    theme: sketchy
    css: styles/base.scss
    toc: true
    highlight-style: github
    breadcrumbs: true
  clean-revealjs:
    self-contained: true
    toc: true
  # revealjs:
  #   themes: 
  #     - clean.scss
  #     - default
  #   highlight-style: github
  #   incremental: true
  #   # css: styles/base.scss
  #   toc: true


filters:
  - filters/global/reveal-tweaks.lua
  - filters/global/speaker-notes.lua